// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using horizonisp.Context;

#nullable disable

namespace horizonisp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530230000_OrdemServicoBoleto")]
    partial class OrdemServicoBoleto
    {
    }
}
