// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using horizonisp.Context;

#nullable disable

namespace horizonisp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530200000_RedeFibra")]
    partial class RedeFibra
    {
    }
}
