// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using horizonisp.Context;

#nullable disable

namespace horizonisp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530260000_ClienteLocalizacao")]
    partial class ClienteLocalizacao
    {
    }
}
