// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using horizonisp.Context;

#nullable disable

namespace horizonisp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("horizonisp.Models.Assinatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoInstalacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LoginPppoe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaPppoe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LoginPppoe")
                        .IsUnique();

                    b.HasIndex("PlanoId");

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("horizonisp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("PortalAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RecuperacaoSenhaExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecuperacaoSenhaToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SenhaPortalHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("horizonisp.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssinaturaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LembreteVencimentoEnviadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AvisoAtrasoEnviadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("BoletoCodigoBarras")
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<string>("BoletoLinhaDigitavel")
                        .HasMaxLength(54)
                        .HasColumnType("nvarchar(54)");

                    b.Property<string>("BoletoNossoNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PixCopiaCola")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("PixExpiracaoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("PixGatewayRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PixTxId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaId", "Referencia")
                        .IsUnique();

                    b.HasIndex("PixTxId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("horizonisp.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Status");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("horizonisp.Models.ChamadoMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AutorTipo")
                        .HasColumnType("int");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("ChamadoMensagens");
                });

            modelBuilder.Entity("horizonisp.Models.PagamentoPix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndToEndId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FaturaId")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EndToEndId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("TxId");

                    b.ToTable("PagamentosPix");
                });

            modelBuilder.Entity("horizonisp.Models.Olt", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Fabricante").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Host").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Localizacao").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<int>("PortaApi").HasColumnType("int");
                    b.Property<string>("SenhaApi").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime?>("UltimaSincronizacao").HasColumnType("datetime2");
                    b.Property<string>("UsuarioApi").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("Nome");
                    b.ToTable("Olts");
                });

            modelBuilder.Entity("horizonisp.Models.Onu", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("AssinaturaId").HasColumnType("int");
                    b.Property<string>("Mac").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<int>("OltId").HasColumnType("int");
                    b.Property<string>("PonPorta").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<string>("Serial").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<int?>("SinalDbm").HasColumnType("int");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<DateTime?>("UltimaAtualizacao").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("AssinaturaId");
                    b.HasIndex("OltId");
                    b.HasIndex("Serial").IsUnique();
                    b.ToTable("Onus");
                });

            modelBuilder.Entity("horizonisp.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("AssinaturaId").HasColumnType("int");
                    b.Property<int?>("ChamadoId").HasColumnType("int");
                    b.Property<int>("ClienteId").HasColumnType("int");
                    b.Property<DateTime?>("DataAgendada").HasColumnType("datetime2");
                    b.Property<DateTime>("DataAbertura").HasColumnType("datetime2");
                    b.Property<DateTime?>("DataConclusao").HasColumnType("datetime2");
                    b.Property<DateTime>("DataAtualizacao").HasColumnType("datetime2");
                    b.Property<string>("Descricao").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("Endereco").IsRequired().HasMaxLength(250).HasColumnType("nvarchar(250)");
                    b.Property<string>("ObservacaoConclusao").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<string>("TecnicoResponsavel").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Titulo").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<int>("Tipo").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("AssinaturaId");
                    b.HasIndex("ChamadoId");
                    b.HasIndex("ClienteId");
                    b.HasIndex("Status");
                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("horizonisp.Models.NotaFiscalServico", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("CodigoVerificacao").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime?>("DataEmissao").HasColumnType("datetime2");
                    b.Property<string>("Discriminacao").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<int>("FaturaId").HasColumnType("int");
                    b.Property<string>("LinkPdf").HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("MensagemErro").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Numero").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<decimal>("Valor").HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("FaturaId").IsUnique();
                    b.HasIndex("Status");
                    b.ToTable("NotasFiscaisServico");
                });

            modelBuilder.Entity("horizonisp.Models.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("VelocidadeDownloadMbps")
                        .HasColumnType("int");

                    b.Property<int>("VelocidadeUploadMbps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("horizonisp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("horizonisp.Models.Assinatura", b =>
                {
                    b.HasOne("horizonisp.Models.Cliente", "Cliente")
                        .WithMany("Assinaturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("horizonisp.Models.Plano", "Plano")
                        .WithMany("Assinaturas")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("horizonisp.Models.Chamado", b =>
                {
                    b.HasOne("horizonisp.Models.Cliente", "Cliente")
                        .WithMany("Chamados")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("horizonisp.Models.ChamadoMensagem", b =>
                {
                    b.HasOne("horizonisp.Models.Chamado", "Chamado")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("horizonisp.Models.Fatura", b =>
                {
                    b.HasOne("horizonisp.Models.Assinatura", "Assinatura")
                        .WithMany("Faturas")
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assinatura");
                });

            modelBuilder.Entity("horizonisp.Models.PagamentoPix", b =>
                {
                    b.HasOne("horizonisp.Models.Fatura", "Fatura")
                        .WithMany("PagamentosPix")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("horizonisp.Models.Onu", b =>
                {
                    b.HasOne("horizonisp.Models.Assinatura", "Assinatura")
                        .WithMany()
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("horizonisp.Models.Olt", "Olt")
                        .WithMany("Onus")
                        .HasForeignKey("OltId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assinatura");
                    b.Navigation("Olt");
                });

            modelBuilder.Entity("horizonisp.Models.OrdemServico", b =>
                {
                    b.HasOne("horizonisp.Models.Assinatura", "Assinatura")
                        .WithMany()
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("horizonisp.Models.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("horizonisp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assinatura");
                    b.Navigation("Chamado");
                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("horizonisp.Models.NotaFiscalServico", b =>
                {
                    b.HasOne("horizonisp.Models.Fatura", "Fatura")
                        .WithOne("NotaFiscalServico")
                        .HasForeignKey("horizonisp.Models.NotaFiscalServico", "FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("horizonisp.Models.Assinatura", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("horizonisp.Models.Chamado", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("horizonisp.Models.Cliente", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("horizonisp.Models.Fatura", b =>
                {
                    b.Navigation("NotaFiscalServico");
                    b.Navigation("PagamentosPix");
                });

            modelBuilder.Entity("horizonisp.Models.Olt", b =>
                {
                    b.Navigation("Onus");
                });

            modelBuilder.Entity("horizonisp.Models.Plano", b =>
                {
                    b.Navigation("Assinaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
